{% set name = "ipyvuedraggable" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a704dfb6d0c27f11cc4d99854a785352df8a80332073e6886570397ecda7bcbd

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python
    - ipyvue >=1.0.0,<2

test:
  imports:
    - ipyvuedraggable

about:
  home: http://github.com/mariobuikhuizen/ipyvuedraggable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Jupyter widget for Vue.Draggable'

  description: |
    Jupyter widget for Vue.Draggable

extra:
  recipe-maintainers:
    - mariobuikhuizen
