travis:
  secure:
    BINSTAR_TOKEN: UqMEIFeyxP/AihnHA3ciJq77QF7Zch/HR1K2edg0bC5pqYiiGetpQomXl7zxZDEwsI6FZW7vel4IBeOJsxALHXP7A/WCvttYLjWBKN8hcrRmfU/V1pbE4GrXXt1VCztOjxZkqavpT9nGGKU+fel9Q1AdIqfuGBvOtXqFDtiZ0L6vTQTmorU1zJr2v8ncnR0n44BtabfZ8p+X9dkqlQFScbRR9nfGmj5+UUuIZNxbnH9JgujQdSVFDr5INNL+iA8Ine5O0vcWHtj6XcmiiCkXZgaDznnqVUTZ5lA6qUPhkPJ4bIuS+vyHUeL9fm2z+MEQn6wBbduO34MJ9OgusMcFzOYX5x4O6ZogwZrMMV1MLOnqICNPBhnnYiCiXO4BJDUXxsvLj0+oxNd3GTV9g1QXvSuZIxlE8ani+VRtyJKpFNcAdNICD1V4Hj7RXkO2jaAKd6/qb3AAfDMR897/AQNV8OFNxTdGjtyUpeJDIl8xz7GPfbaMwlU8fxKjTRkyeM1lPweLeoJ0Qmfj/MzQDRCxiIMDj4c89MI/6x0EVRyWEElylRqhKizGiCDOUHiPZnfgJ2HMF6vv9vGfHBtmtFbRqKLIs3ZaUfwdI5PVURQsfJ56lVTUcTnV2k0IQG0cfh7iDVzLed4BmKHdAy3cf8IUjtGNRwi02yI55SAL3U1fHts=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
